[package]
name = "mini-redis"
version = "0.1.0"
edition = "2021"
default-run = "server"

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
bytes = "1"

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "client"
path = "client-example/src/main.rs"
